### ISSUE TITLE
phpenv install --releases produces no result

### ISSUE THREAD

**Issue by Abuelodelanada** [phpenv/phpenv#43]
➜  ~  phpenv install --releases
phpenv v0.0.4-dev

```
                init extensions  the cloning of repositories for additional extensions  
```

**Comment by vluzrmos** [comment]
It's because the default branch on github is "dev", instead of "master", you just have to "git checkout master", to fix it.

**Comment by mikeyjk** [comment]
> It's because the default branch on github is "dev", instead of "master", you just have to "git checkout master", to fix it.

Worked for me on Centos 6.5.
So far anyway. Still cloning.

**Comment by mrugeshrocks** [comment]
Switching to master works :+1:

**Comment by debo** [comment]
Or you can switch to [this fork](https://github.com/madumlao/phpenv) that is currently actively developed.

**Comment by staabm** [comment]
same issue here

**Comment by debo** [comment]
@staabm switch to the actively maintained branch I suggested, that should sort you out. This project unfortunately is no longer mantained

**Comment by staabm** [comment]
@debo thx for your feedback. I followed the instructions in the readme of the fork (including plugins dir etc.), but it doesnt work for me either. I have the same issue as with the origin repos.

**Comment by debo** [comment]
@staabm what issue exactly? No output at all? Or something else?

**Comment by staabm** [comment]
@debo excatly the same issue as before.

does the fork only work because of this Installation step "1.1 ..plugins.." or do I also need to clone `phpenv` itself from the fork. the instructions in the readme of the fork still mention phpenv/phpenv instead of `madumlao/phpenv`. is this intended?

**Comment by staabm** [comment]
@debo fixed with https://github.com/madumlao/phpenv/pull/4 , thx for your hlep

**Comment by debo** [comment]
@staabm yeah that was an overlooked problem. I'm glad you solved the problem.

**Comment by GBeushausen** [comment]
What's wrong with this project? This error is known since 2013(!!!) and it's still not fixed? I tried on two different Linux machines and it's not possible to get a list of releases.

**Comment by Abuelodelanada** [comment]
@GBeushausen the project seems to be abandoned. The last commit is November 2013

**Comment by GBeushausen** [comment]
@Abuelodelanada Thanks. I see.

**Comment by debo** [comment]
@GBeushausen you can see the full conversation around it [here](https://github.com/phpenv/phpenv/issues/57) if you want to know more.

**Comment by madumlao** [comment]
Closing as a duplicate of #57.

phpenv install should now be working with the latest versions pulled by [phpenv-installer](https://github.com/phpenv/phpenv-installer).
